### ISSUE TITLE
Add ores suspension Islands

### ISSUE THREAD

**Issue by Pantyhose-X** [Treer/cloudlands#10]
My server uses "mapgen singlenode" + ”cloudlands“ without ores, there is no way to survive. There is no way to make many things that need ores

**Comment by Treer** [comment]
Ores will generate if you have the "Generate ores inside islands" setting turned on (Settings → All Settings → Content: Mods → cloudlands → Generate ores inside islands - patches of dirt, sand etc.)

However, that's not enough. The problem is most games define their ores to be at limited altitudes. I thought that since you were running singlenode then a quick workaround would be to just set the island height to -500, but I tried that and the islands have no dirt or plants because the game also gives those biomes an altitude. They did have lots of ores tho!
![image](https://user-images.githubusercontent.com/6390507/185943131-6648b1a0-3090-4ffc-9a5b-ad5fb73762e0.png)


So, what you'll need to do is raise the altitude of the game's ores. I'm not sure which game you're using, but if it was minetest_game for example, then you would edit the `y_min` and `y_max` in [these ore definitions](https://github.com/minetest/minetest_game/blob/master/mods/default/mapgen.lua#L411-L884)

If it's Minetest_game you could do a search replace of `y_min          = 1025` to `y_min          = 200`, which would drop the floatlands ores down to cloudlands altitude.

(or perhaps copy lines 411 to 884 and make a duplicate set of ore definitions at the height you like in your own file)

It's the game that decides where ores should appear, and cloudlands can't place them because different games create different ores, but you can at least edit the game. This way you get to adjust the scarcity too.
