### ISSUE TITLE
finishGenNode crashes

### ISSUE THREAD

**Issue by NathanSalapat** [Treer/cloudlands#5]
I am running this mod on my server and keep getting crashes like this.
`2020-04-06 00:22:20: ERROR[Main]: ServerError: AsyncErr: Lua: finishGenNode name is not set or is not a string!`
The server is running 5.2.0, though it had the issues with the 5.2 dev-build as well. I believe it has something to deal with the mapgen aliases referencing nodes that don't exist. I fixed most of the problems by removing the references to the MCL and Mapgen nodes, but am still getting crashes. Unfortunately the error from the sever doesn't give me much to work with. In singleplayer the error returns the offending node that couldn't be found.
The error can take a while to find though, and sometimes the server runs for days without issue, until somebody happens to visit a specific spot in the world.

**Comment by Treer** [comment]
Thanks @NathanSalapat , I've added fixes for 5.2.0 compatibility, but have not seen this error.

I've cruised through a dummy map and forced generation of rare secrets and trees, but it's possible this is caused by the force-aliasing in another mod, so if the problem still happens and you have any suspicions of which mod may be calling register_alias_force() on something cloudlands uses, let me know.

moreblocks breaks nether but doesn't appear to break cloudlands

**Comment by NathanSalapat** [comment]
I'll update the code on my server and report back. My players have a few places they've saved that they can visit to crash the server, so I'll have them try that and see what happens.

**Comment by NathanSalapat** [comment]
Appears to be fixed. My players can't crash the server anymore. Thank you.
